// <auto-generated />
using J3m_BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace J3m_BE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251024091716_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("J3m_BE.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            AdminId = 1,
                            PasswordHash = "admin123",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("J3m_BE.Models.Allergy", b =>
                {
                    b.Property<int>("AllergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllergyId"));

                    b.Property<string>("AllergyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AllergyId");

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            AllergyId = 1,
                            AllergyName = "Gluten"
                        },
                        new
                        {
                            AllergyId = 2,
                            AllergyName = "Diary(milk protein)"
                        },
                        new
                        {
                            AllergyId = 3,
                            AllergyName = "Lactose intolerance"
                        },
                        new
                        {
                            AllergyId = 4,
                            AllergyName = "Wheat"
                        },
                        new
                        {
                            AllergyId = 5,
                            AllergyName = "Egg"
                        },
                        new
                        {
                            AllergyId = 6,
                            AllergyName = "Shellfish"
                        },
                        new
                        {
                            AllergyId = 7,
                            AllergyName = "Fish"
                        },
                        new
                        {
                            AllergyId = 8,
                            AllergyName = "Nuts"
                        },
                        new
                        {
                            AllergyId = 9,
                            AllergyName = "Peanuts"
                        },
                        new
                        {
                            AllergyId = 10,
                            AllergyName = "Celery"
                        });
                });

            modelBuilder.Entity("J3m_BE.Models.Diet", b =>
                {
                    b.Property<int>("DietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DietId"));

                    b.Property<string>("DietName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DietId");

                    b.ToTable("Diets");

                    b.HasData(
                        new
                        {
                            DietId = 1,
                            DietName = "Keto"
                        },
                        new
                        {
                            DietId = 2,
                            DietName = "Paleo"
                        },
                        new
                        {
                            DietId = 3,
                            DietName = "Pescetarian"
                        },
                        new
                        {
                            DietId = 4,
                            DietName = "Vegan"
                        },
                        new
                        {
                            DietId = 5,
                            DietName = "Vegetarian"
                        });
                });

            modelBuilder.Entity("J3m_BE.Models.FoodGroup", b =>
                {
                    b.Property<int>("FoodGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodGroupId"));

                    b.Property<string>("FoodGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FoodGroupId");

                    b.ToTable("FoodGroups");

                    b.HasData(
                        new
                        {
                            FoodGroupId = 1,
                            FoodGroupName = "Fruits"
                        },
                        new
                        {
                            FoodGroupId = 2,
                            FoodGroupName = "Vegetables"
                        },
                        new
                        {
                            FoodGroupId = 3,
                            FoodGroupName = "Grains"
                        },
                        new
                        {
                            FoodGroupId = 4,
                            FoodGroupName = "Meats/Egg"
                        },
                        new
                        {
                            FoodGroupId = 5,
                            FoodGroupName = "Dairy"
                        },
                        new
                        {
                            FoodGroupId = 6,
                            FoodGroupName = "Nuts/Seed"
                        },
                        new
                        {
                            FoodGroupId = 7,
                            FoodGroupName = "Legume"
                        });
                });

            modelBuilder.Entity("J3m_BE.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<int>("FoodGroupId")
                        .HasColumnType("int");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IngredientId");

                    b.HasIndex("FoodGroupId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.DietRecipe", b =>
                {
                    b.Property<int>("DietId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("DietId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("DietRecipes");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.IngredientAllergy", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("AllergyId")
                        .HasColumnType("int");

                    b.HasKey("IngredientId", "AllergyId");

                    b.HasIndex("AllergyId");

                    b.ToTable("IngredientAllergies");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.IngredientNutrientGroup", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("NutrientGroupId")
                        .HasColumnType("int");

                    b.HasKey("IngredientId", "NutrientGroupId");

                    b.HasIndex("NutrientGroupId");

                    b.ToTable("IngredientNutrientGroups");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.IngredientRecipe", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Measurements")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IngredientId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("IngredientRecipes");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.UserRecipe", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("UserRecipes");
                });

            modelBuilder.Entity("J3m_BE.Models.NutrientGroup", b =>
                {
                    b.Property<int>("NutrientGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NutrientGroupId"));

                    b.Property<string>("NutrientGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NutrientGroupId");

                    b.ToTable("NutrientGroups");

                    b.HasData(
                        new
                        {
                            NutrientGroupId = 1,
                            NutrientGroupName = "Carbohydrates"
                        },
                        new
                        {
                            NutrientGroupId = 2,
                            NutrientGroupName = "Protein"
                        },
                        new
                        {
                            NutrientGroupId = 3,
                            NutrientGroupName = "Fats and oils"
                        },
                        new
                        {
                            NutrientGroupId = 4,
                            NutrientGroupName = "Dietary fibre"
                        });
                });

            modelBuilder.Entity("J3m_BE.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("J3m_BE.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            PasswordHash = "user1",
                            Username = "user1"
                        },
                        new
                        {
                            UserId = 2,
                            PasswordHash = "user2",
                            Username = "user2"
                        },
                        new
                        {
                            UserId = 3,
                            PasswordHash = "user3",
                            Username = "user3"
                        });
                });

            modelBuilder.Entity("J3m_BE.Models.Ingredient", b =>
                {
                    b.HasOne("J3m_BE.Models.FoodGroup", "FoodGroup")
                        .WithMany("Ingredients")
                        .HasForeignKey("FoodGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodGroup");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.DietRecipe", b =>
                {
                    b.HasOne("J3m_BE.Models.Diet", "Diet")
                        .WithMany("RecipeLinks")
                        .HasForeignKey("DietId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("J3m_BE.Models.Recipe", "Recipe")
                        .WithMany("DietLinks")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diet");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.IngredientAllergy", b =>
                {
                    b.HasOne("J3m_BE.Models.Allergy", "Allergy")
                        .WithMany("IngredientLinks")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("J3m_BE.Models.Ingredient", "Ingredient")
                        .WithMany("AllergyLinks")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.IngredientNutrientGroup", b =>
                {
                    b.HasOne("J3m_BE.Models.Ingredient", "Ingredient")
                        .WithMany("NutrientLinks")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("J3m_BE.Models.NutrientGroup", "NutrientGroup")
                        .WithMany("IngredientLinks")
                        .HasForeignKey("NutrientGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("NutrientGroup");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.IngredientRecipe", b =>
                {
                    b.HasOne("J3m_BE.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeLinks")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("J3m_BE.Models.Recipe", "Recipe")
                        .WithMany("IngredientLinks")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.UserRecipe", b =>
                {
                    b.HasOne("J3m_BE.Models.Recipe", "Recipe")
                        .WithMany("UserLinks")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("J3m_BE.Models.User", "User")
                        .WithMany("UserRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("J3m_BE.Models.Allergy", b =>
                {
                    b.Navigation("IngredientLinks");
                });

            modelBuilder.Entity("J3m_BE.Models.Diet", b =>
                {
                    b.Navigation("RecipeLinks");
                });

            modelBuilder.Entity("J3m_BE.Models.FoodGroup", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("J3m_BE.Models.Ingredient", b =>
                {
                    b.Navigation("AllergyLinks");

                    b.Navigation("NutrientLinks");

                    b.Navigation("RecipeLinks");
                });

            modelBuilder.Entity("J3m_BE.Models.NutrientGroup", b =>
                {
                    b.Navigation("IngredientLinks");
                });

            modelBuilder.Entity("J3m_BE.Models.Recipe", b =>
                {
                    b.Navigation("DietLinks");

                    b.Navigation("IngredientLinks");

                    b.Navigation("UserLinks");
                });

            modelBuilder.Entity("J3m_BE.Models.User", b =>
                {
                    b.Navigation("UserRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
