// <auto-generated />
using System;
using J3m_BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace J3m_BE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251120112622_InitTest")]
    partial class InitTest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("J3m_BE.Models.Allergy", b =>
                {
                    b.Property<int>("AllergyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllergyId"));

                    b.Property<string>("AllergyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AllergyId");

                    b.ToTable("Allergies");

                    b.HasData(
                        new
                        {
                            AllergyId = 1,
                            AllergyName = "Gluten"
                        },
                        new
                        {
                            AllergyId = 2,
                            AllergyName = "Diary(milk protein)"
                        },
                        new
                        {
                            AllergyId = 3,
                            AllergyName = "Lactose intolerance"
                        },
                        new
                        {
                            AllergyId = 4,
                            AllergyName = "Wheat"
                        },
                        new
                        {
                            AllergyId = 5,
                            AllergyName = "Egg"
                        },
                        new
                        {
                            AllergyId = 6,
                            AllergyName = "Shellfish"
                        },
                        new
                        {
                            AllergyId = 7,
                            AllergyName = "Fish"
                        },
                        new
                        {
                            AllergyId = 8,
                            AllergyName = "Nuts"
                        },
                        new
                        {
                            AllergyId = 9,
                            AllergyName = "Peanuts"
                        },
                        new
                        {
                            AllergyId = 10,
                            AllergyName = "Celery"
                        });
                });

            modelBuilder.Entity("J3m_BE.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("J3m_BE.Models.Diet", b =>
                {
                    b.Property<int>("DietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DietId"));

                    b.Property<string>("DietName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DietId");

                    b.ToTable("Diets");

                    b.HasData(
                        new
                        {
                            DietId = 1,
                            DietName = "Keto"
                        },
                        new
                        {
                            DietId = 2,
                            DietName = "Paleo"
                        },
                        new
                        {
                            DietId = 3,
                            DietName = "Pescetarian"
                        },
                        new
                        {
                            DietId = 4,
                            DietName = "Vegan"
                        },
                        new
                        {
                            DietId = 5,
                            DietName = "Vegetarian"
                        });
                });

            modelBuilder.Entity("J3m_BE.Models.FoodGroup", b =>
                {
                    b.Property<int>("FoodGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FoodGroupId"));

                    b.Property<string>("FoodGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FoodGroupId");

                    b.ToTable("FoodGroups");

                    b.HasData(
                        new
                        {
                            FoodGroupId = 1,
                            FoodGroupName = "Fruits"
                        },
                        new
                        {
                            FoodGroupId = 2,
                            FoodGroupName = "Vegetables"
                        },
                        new
                        {
                            FoodGroupId = 3,
                            FoodGroupName = "Grains"
                        },
                        new
                        {
                            FoodGroupId = 4,
                            FoodGroupName = "Meats/Egg"
                        },
                        new
                        {
                            FoodGroupId = 5,
                            FoodGroupName = "Dairy"
                        },
                        new
                        {
                            FoodGroupId = 6,
                            FoodGroupName = "Nuts/Seed"
                        },
                        new
                        {
                            FoodGroupId = 7,
                            FoodGroupName = "Legume"
                        });
                });

            modelBuilder.Entity("J3m_BE.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<int?>("FoodGroupId")
                        .HasColumnType("int");

                    b.Property<string>("IngredientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IngredientId");

                    b.HasIndex("FoodGroupId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.DietRecipe", b =>
                {
                    b.Property<int>("DietId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("DietId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("DietRecipes");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.IngredientAllergy", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("AllergyId")
                        .HasColumnType("int");

                    b.HasKey("IngredientId", "AllergyId");

                    b.HasIndex("AllergyId");

                    b.ToTable("IngredientAllergies");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.IngredientNutrientGroup", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("NutrientGroupId")
                        .HasColumnType("int");

                    b.HasKey("IngredientId", "NutrientGroupId");

                    b.HasIndex("NutrientGroupId");

                    b.ToTable("IngredientNutrientGroups");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.IngredientRecipe", b =>
                {
                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Measurement")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IngredientId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("IngredientRecipes");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.UserRecipe", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "RecipeId");

                    b.HasIndex("RecipeId");

                    b.ToTable("UserRecipes");
                });

            modelBuilder.Entity("J3m_BE.Models.NutrientGroup", b =>
                {
                    b.Property<int>("NutrientGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NutrientGroupId"));

                    b.Property<string>("NutrientGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NutrientGroupId");

                    b.ToTable("NutrientGroups");

                    b.HasData(
                        new
                        {
                            NutrientGroupId = 1,
                            NutrientGroupName = "Carbohydrates"
                        },
                        new
                        {
                            NutrientGroupId = 2,
                            NutrientGroupName = "Protein"
                        },
                        new
                        {
                            NutrientGroupId = 3,
                            NutrientGroupName = "Fats and oils"
                        },
                        new
                        {
                            NutrientGroupId = 4,
                            NutrientGroupName = "Dietary fibre"
                        });
                });

            modelBuilder.Entity("J3m_BE.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Instruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("int");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RecipeId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("J3m_BE.Models.Ingredient", b =>
                {
                    b.HasOne("J3m_BE.Models.FoodGroup", "FoodGroup")
                        .WithMany("Ingredients")
                        .HasForeignKey("FoodGroupId");

                    b.Navigation("FoodGroup");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.DietRecipe", b =>
                {
                    b.HasOne("J3m_BE.Models.Diet", "Diet")
                        .WithMany("RecipeLinks")
                        .HasForeignKey("DietId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("J3m_BE.Models.Recipe", "Recipe")
                        .WithMany("DietLinks")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diet");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.IngredientAllergy", b =>
                {
                    b.HasOne("J3m_BE.Models.Allergy", "Allergy")
                        .WithMany("IngredientLinks")
                        .HasForeignKey("AllergyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("J3m_BE.Models.Ingredient", "Ingredient")
                        .WithMany("AllergyLinks")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergy");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.IngredientNutrientGroup", b =>
                {
                    b.HasOne("J3m_BE.Models.Ingredient", "Ingredient")
                        .WithMany("NutrientLinks")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("J3m_BE.Models.NutrientGroup", "NutrientGroup")
                        .WithMany("IngredientLinks")
                        .HasForeignKey("NutrientGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("NutrientGroup");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.IngredientRecipe", b =>
                {
                    b.HasOne("J3m_BE.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeLinks")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("J3m_BE.Models.Recipe", "Recipe")
                        .WithMany("IngredientLinks")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("J3m_BE.Models.Links.UserRecipe", b =>
                {
                    b.HasOne("J3m_BE.Models.Recipe", "Recipe")
                        .WithMany("UserLinks")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("J3m_BE.Models.AppUser", "User")
                        .WithMany("UserRecipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("J3m_BE.Models.Recipe", b =>
                {
                    b.HasOne("J3m_BE.Models.AppUser", "CreatedByUser")
                        .WithMany("CreateRecipes")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("J3m_BE.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("J3m_BE.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("J3m_BE.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("J3m_BE.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("J3m_BE.Models.Allergy", b =>
                {
                    b.Navigation("IngredientLinks");
                });

            modelBuilder.Entity("J3m_BE.Models.AppUser", b =>
                {
                    b.Navigation("CreateRecipes");

                    b.Navigation("UserRecipes");
                });

            modelBuilder.Entity("J3m_BE.Models.Diet", b =>
                {
                    b.Navigation("RecipeLinks");
                });

            modelBuilder.Entity("J3m_BE.Models.FoodGroup", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("J3m_BE.Models.Ingredient", b =>
                {
                    b.Navigation("AllergyLinks");

                    b.Navigation("NutrientLinks");

                    b.Navigation("RecipeLinks");
                });

            modelBuilder.Entity("J3m_BE.Models.NutrientGroup", b =>
                {
                    b.Navigation("IngredientLinks");
                });

            modelBuilder.Entity("J3m_BE.Models.Recipe", b =>
                {
                    b.Navigation("DietLinks");

                    b.Navigation("IngredientLinks");

                    b.Navigation("UserLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
